/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "stack.h"
#include "faults.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern uint32_t task_handlers[];
extern uint32_t psp_of_task[];
uint8_t current_task = 0; //task1 is running


void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

void init_systick_timer(uint32_t tick_hz);
void switch_sp_to_psp(void);

int main(void)
{
    print_stack_info();

    enable_processor_faults(1, 1, 1);

    init_scheduler_stack(SCHED_STACK_START);

    //creating addray of handlers
    task_handlers[0] = (uint32_t)task1_handler;
    task_handlers[1] = (uint32_t)task2_handler;
    task_handlers[2] = (uint32_t)task3_handler;
    task_handlers[3] = (uint32_t)task4_handler;


    init_task_stack();

    init_systick_timer(TICK_HZ);

    switch_sp_to_psp();

    task1_handler();
    /* Loop forever */
	for(;;);
}

void task1_handler(void)
{
    while(1)
    {
        printf("Task 1\n");
    }
}

void task2_handler(void)
{
    while(1)
    {
        printf("Task 2\n");
    }
}

void task3_handler(void)
{
    while(1)
    {
        printf("Task 3\n");
    }
}

void task4_handler(void)
{
    while(1)
    {
        printf("Task 4\n");
    }
}

