/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

void init_systick_timer(uint32_t tick_hz);
__attribute__((naked)) void init_scheduler_stack(uint32_t scheduler_stack_start);
void init_task_stack();

uint32_t psp_of_task[MAX_TASKS] = {T1_STACK_START, T2_STACK_START, T3_STACK_START, T4_STACK_START};

int main(void)
{
    init_scheduler_stack(SCHED_STACK_START);

    init_task_stack();
    init_systick_timer(TICK_HZ);
    /* Loop forever */
	for(;;);
}

void task1_handler(void)
{
    while(1)
    {
        printf("Task 1\n");
    }
}

void task2_handler(void)
{
    while(1)
    {
        printf("Task 2\n");
    }
}

void task3_handler(void)
{
    while(1)
    {
        printf("Task 3\n");
    }
}

void task4_handler(void)
{
    while(1)
    {
        printf("Task 4\n");
    }
}

void SysTick_Handler(void)
{
    printf("In SysTick Handler\n");
}

void init_systick_timer(uint32_t tick_hz)
{
    //Systick reload value register
    uint32_t *pSRVR = (uint32_t *)0xE000E014;
    uint32_t *pSCVR = (uint32_t *)0xE000E010;
    uint32_t count_value = (SYSTICK_TIM_CLK/tick_hz) -1;

    //clear value of SVR
    *pSRVR &= ~(0xffffffff);

    //load value into SVR
    *pSRVR |= count_value;

    //do some setting in SYST_CVR 
    *pSCVR |= (1 << 1) | (1 << 2); //enables systick exception request and indicates clock source, respectivley.

    //enables systick
    *pSCVR |= (1 << 0); //enable systick
}

__attribute__((naked)) void init_scheduler_stack(uint32_t scheduler_stack_start)
{
    //first argument passed to this function is r0 
    //__asm volatile("MSR MSP,R0"); 
    __asm volatile ("MSR MSP,R0": : "r"(scheduler_stack_start) : );
    //Branch indirect back to main, which is stored in LR
    __asm volatile ("BX LR");
}

void init_task_stack(void)
{
	uint32_t *pPSP;
	for(int i = 0; i < MAX_TASKS; i++)
	{
		pPSP = (uint32_t *)psp_of_tasks[i];
	}
}
