/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f407xx.h"
#include "uart_drivers.h"
#include "spi_drivers.h"
#include "gpio_drivers.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint8_t string[] = "hello\n\r";
	printf((char*)string);
	USART_Init(USART2);
	SPI_Init(SPI1);
	gpio_test_init();


	uputs(string);
    /* Loop forever */
	while(1)
	{
		green_led_toggle();
		SPI1_Transmit(string);
		uputs(string);
		for(int i = 0; i < 1000000; i++){};

		//re-enable EXTI0 interrupt after handler
		enable_interrupt((uint8_t)IRQ_NO_EXTI0);

	};
}

void EXTI0_IRQHandler()
{
	uint8_t gp[] = "gpio\n\r";
	uputs(gp);
	blue_led_toggle();
	for(int i = 0; i < 1000000; i++){};
	clear_interrupt((uint8_t)IRQ_NO_EXTI0);
	blue_led_toggle();

}
